### PR TITLE
make lib php7 compatible

### PR DESCRIPTION
**Pull request by albertovincenzi**

### CODE REVIEW

**Comment by carlos-mora** [comment]
given 7.3 has no support and 7.4 has entered "security only", may be it's a good time to check the lib against 8.x series.

**Comment by masterix21** [comment]
@albertovincenzi, sorry but it's not enough. 

Check yourself: https://app.travis-ci.com/github/masterix21/green-pass

I agree with @carlos-mora, so maybe better to keep the 8 version only.

**Comment by albertovincenzi** [comment]
I would agree with both of you but according to last stats, php8.0 adoptions still lower than 10% so if php8 would be a requirement, It would restrict this library for just a bunch of projects.

Minimum requirements might be 7.4 as it is considered a very stable version

**Comment by PF-Enriquez** [comment]
I agree with @albertovincenzi, very few systems are already on PHP 8.0. PHP 7.3 or 4 seems to be a legit choice.

**Comment by carlos-mora** [comment]
7.3 is dead. 7.4 is in the way to. Staying in 7.x is whorthless. May be support can be given, but it's _far_ more important to have support for _current_ versions, that is 8.x. Those who don't want to stay safe and use a supported and updated PHP version can't be the target of the package. I know there are people still using even 5.x, but that's not serious.

**Comment by carlos-mora** [comment]
📢Releases for the rest of the year:
📅Nov 18: 7.3.33, 7.4.26 and 8.0.13
🎉Nov 25: 8.1.0!!!
🔒Nov 28: **Security-only support for 7.4 starts**
🛑Dec 06: **End of life for 7.3**
📅Dec 16: 7.4.27, 8.0.14, and 8.1.1
📅Jan 20: 8.0.15 and 8.1.2 (and maybe 7.4.28 as security release)

https://www.php.net/supported-versions.php

People seems to not paying too much attention to PHP life cycle.

**Comment by albertovincenzi** [comment]
Dear @carlos-mora, I think that you are somehow joking 😄 
Making a library compatible with the previous php version has nothing to do with what you said.
I don't agree its important to make a library compatible with the latest php version: that is just a must... no need to discuss that.

In any case, I made a PR that just makes the lib compatible with 7.x version. Drop a php previous version compatibility should be done only when:

- the effort is high
- the compatibility may open to security issues or bugs

In any case, we are going OT. If the maintainer likes the PR, he is free to merge.

**Comment by masterix21** [comment]
Married @carlos-mora's opinion: I prefer to keep the library compatible with PHP8 or above.

Thanks, @albertovincenzi for your time on it.

**Pull request closed without merging**
